name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"  # Se ejecuta cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.1  # ✅ Volvemos a la última versión estable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
